/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;
import business.*;
import java.awt.Dimension;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author maria
 */
public class AdminPannel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPannel
     */
    public AdminPannel() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        nameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        passText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        numeField = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();
        passField = new javax.swing.JLabel();
        addressField = new javax.swing.JLabel();
        phoneField = new javax.swing.JLabel();
        userIdField = new javax.swing.JLabel();
        userIdText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateToAButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        listOneButton = new javax.swing.JButton();
        listMoreButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        addAdminButton = new javax.swing.JButton();
        updateToEButton = new javax.swing.JButton();
        reportButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        numeField.setBackground(new java.awt.Color(0, 153, 153));
        numeField.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        numeField.setForeground(new java.awt.Color(0, 102, 102));
        numeField.setText("Name");

        emailField.setBackground(new java.awt.Color(0, 153, 153));
        emailField.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(0, 102, 102));
        emailField.setText("Email");

        passField.setBackground(new java.awt.Color(0, 153, 153));
        passField.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        passField.setForeground(new java.awt.Color(0, 102, 102));
        passField.setText("Password");

        addressField.setBackground(new java.awt.Color(0, 153, 153));
        addressField.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        addressField.setForeground(new java.awt.Color(0, 102, 102));
        addressField.setText("Address");

        phoneField.setBackground(new java.awt.Color(0, 153, 153));
        phoneField.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        phoneField.setForeground(new java.awt.Color(0, 102, 102));
        phoneField.setText("Phone");

        userIdField.setBackground(new java.awt.Color(0, 102, 102));
        userIdField.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        userIdField.setForeground(new java.awt.Color(0, 102, 102));
        userIdField.setText("UserID:");

        addButton.setBackground(new java.awt.Color(0, 102, 102));
        addButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        addButton.setText("Add User");
        addButton.setToolTipText("Fill the text fields if you want to add a user");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateToAButton.setBackground(new java.awt.Color(0, 102, 102));
        updateToAButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        updateToAButton.setText("Update User to ADMIN");
        updateToAButton.setToolTipText("Fill the text fields if you want to update a user");
        updateToAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateToAButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(0, 102, 102));
        deleteButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        deleteButton.setText("Delete User");
        deleteButton.setToolTipText("Fill in UserId for delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        listOneButton.setBackground(new java.awt.Color(0, 102, 102));
        listOneButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        listOneButton.setText("List a Users by ID");
        listOneButton.setToolTipText("Fill in UserId for list a specific User");
        listOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOneButtonActionPerformed(evt);
            }
        });

        listMoreButton.setBackground(new java.awt.Color(0, 102, 102));
        listMoreButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        listMoreButton.setText("List Users");
        listMoreButton.setToolTipText("Lists all Users");
        listMoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMoreButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(0, 102, 102));
        logoutButton.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        logoutButton.setText("LOG OUT");
        logoutButton.setToolTipText("Press for LOG-OUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        addAdminButton.setBackground(new java.awt.Color(0, 102, 102));
        addAdminButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        addAdminButton.setText("Add Admin");
        addAdminButton.setToolTipText("Fill the text fields if you want to add an admin");
        addAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminButtonActionPerformed(evt);
            }
        });

        updateToEButton.setBackground(new java.awt.Color(0, 102, 102));
        updateToEButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        updateToEButton.setText("Update User to Employee");
        updateToEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateToEButtonActionPerformed(evt);
            }
        });

        reportButton.setBackground(new java.awt.Color(0, 102, 102));
        reportButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        reportButton.setText("Report about a user");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        jMenu2.setText("Info");

        jMenuItem1.setText("ADD");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(numeField))
                                .addComponent(emailField, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(passField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneField)
                                    .addComponent(addressField))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phoneText)
                                    .addComponent(addressText)
                                    .addComponent(userIdText)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateToAButton)
                            .addComponent(updateToEButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listMoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listOneButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportButton))))
                .addContainerGap(907, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addressText, emailText, nameText, passText, phoneText});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {updateToAButton, updateToEButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {listMoreButton, listOneButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, reportButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeField)
                    .addComponent(addressField)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField)
                    .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passField)
                    .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateToAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listMoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAdminButton)
                            .addComponent(listOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateToEButton)
                            .addComponent(reportButton))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(logoutButton)
                .addGap(31, 31, 31))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addressText, emailText, nameText, passText, phoneText});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addAdminButton, addButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteButton, listMoreButton, reportButton, updateToAButton, updateToEButton});

        logoutButton.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void listOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOneButtonActionPerformed
        // TODO add your handling code here:
        int id=parseInt(userIdText.getText());
        User user=new User();
        DefaultTableModel userModel=user.getUser(id);
        JTable userTable=new JTable(userModel);
        JDialog dialog=new JDialog();
        dialog.setPreferredSize(new Dimension(650,300));
	dialog.setLocationRelativeTo(null);
	dialog.setTitle("User with "+id+" id");
        JScrollPane scrollPane3 = new JScrollPane(userTable);
        scrollPane3.setBounds(10, 50, 950, 120);
	scrollPane3.setEnabled(false);
	dialog.add(scrollPane3);
	dialog.pack();
	dialog.setVisible(true);
    }//GEN-LAST:event_listOneButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        LOGIN login=new LOGIN();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        User user=new User();
        String nume =nameText.getText();
        String email =emailText.getText();
        String password =passText.getText();
        String address =addressText.getText();
        String phone =phoneText.getText();
        String raspuns;
        raspuns=user.insert(nume, email, password, address, phone, "not admin");
        if (raspuns.equals("Creat cu succes"))
            JOptionPane.showMessageDialog(null, "Adaugat cu succes");
        else
            JOptionPane.showMessageDialog(null, "Nu s-a putut face adaugarea");
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void addAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminButtonActionPerformed
        // TODO add your handling code here:
         User user=new User();
        String nume =nameText.getText();
        String email =emailText.getText();
        String password =passText.getText();
        String address =addressText.getText();
        String phone =phoneText.getText();
        String raspuns;
        raspuns=user.insert(nume, email, password, address, phone, "admin");
        if (raspuns.equals("Creat cu succes"))
            JOptionPane.showMessageDialog(null, "Adaugat cu succes");
        else
            JOptionPane.showMessageDialog(null, "Nu s-a putut face adaugarea");
    }//GEN-LAST:event_addAdminButtonActionPerformed

    private void listMoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMoreButtonActionPerformed
        // TODO add your handling code here:
        User user=new User();
        DefaultTableModel userModel=user.getUsers();
        JTable userTable=new JTable(userModel);
        JDialog dialog=new JDialog();
        dialog.setPreferredSize(new Dimension(650,300));
	dialog.setLocationRelativeTo(null);
	dialog.setTitle("Users");
        JScrollPane scrollPane3 = new JScrollPane(userTable);
        scrollPane3.setBounds(10, 50, 950, 120);
	scrollPane3.setEnabled(false);
	dialog.add(scrollPane3);
	dialog.pack();
	dialog.setVisible(true);
        //JOptionPane.showMessageDialog(null, userTable);
        //this.add(userTable);
        //this.setVisible(true);
        //userTable.setVisible(true);
        //this.setViewportView(userTable);
    }//GEN-LAST:event_listMoreButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Pentru a adauga un user, se introduc datele si se apasa pe Add User sau Add Admin");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int id=parseInt(userIdText.getText());
        User user=new User();
        String rezultat=user.delete(id);
        if(rezultat.equals("Sters cu succes"))
        {
            JOptionPane.showMessageDialog(null, "Sters cu succes");
        }
        else
        JOptionPane.showMessageDialog(null, "Nu s-a putut face stergerea");
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateToAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateToAButtonActionPerformed
        // TODO add your handling code here:
        int id=parseInt(userIdText.getText());
        String nume =nameText.getText();
        String email =emailText.getText();
        String password =passText.getText();
        String address =addressText.getText();
        String phone =phoneText.getText();
        User user=new User();
        String rezultat=user.update(id, nume, email, password, address, phone, "admin");
        if(rezultat.equals("Actualizat cu succes"))
        {
            JOptionPane.showMessageDialog(null, "Update cu succes");
        }
        else
        JOptionPane.showMessageDialog(null, "Nu s-a putut face update");
    }//GEN-LAST:event_updateToAButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        // TODO add your handling code here:
        int id=parseInt(userIdText.getText());
        User user=new User();
        DefaultTableModel userModel=user.Raport(id);
        JTable userTable=new JTable(userModel);
        JDialog dialog=new JDialog();
        dialog.setPreferredSize(new Dimension(650,300));
	dialog.setLocationRelativeTo(null);
	dialog.setTitle("User with "+id+" id");
        JScrollPane scrollPane3 = new JScrollPane(userTable);
        scrollPane3.setBounds(10, 50, 950, 120);
	scrollPane3.setEnabled(false);
	dialog.add(scrollPane3);
	dialog.pack();
	dialog.setVisible(true);
    }//GEN-LAST:event_reportButtonActionPerformed

    private void updateToEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateToEButtonActionPerformed
        // TODO add your handling code here:
        int id=parseInt(userIdText.getText());
        String nume =nameText.getText();
        String email =emailText.getText();
        String password =passText.getText();
        String address =addressText.getText();
        String phone =phoneText.getText();
        User user=new User();
        String rezultat=user.update(id, nume, email, password, address, phone, "not admin");
        if(rezultat.equals("Actualizat cu succes"))
        {
            JOptionPane.showMessageDialog(null, "Update cu succes");
        }
        else
        JOptionPane.showMessageDialog(null, "Nu s-a putut face update");
    }//GEN-LAST:event_updateToEButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new AdminPannel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdminButton;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressField;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel emailField;
    private javax.swing.JTextField emailText;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton listMoreButton;
    private javax.swing.JButton listOneButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel numeField;
    private javax.swing.JLabel passField;
    private javax.swing.JTextField passText;
    private javax.swing.JLabel phoneField;
    private javax.swing.JTextField phoneText;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton updateToAButton;
    private javax.swing.JButton updateToEButton;
    private javax.swing.JLabel userIdField;
    private javax.swing.JTextField userIdText;
    // End of variables declaration//GEN-END:variables
}
