/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import business.MangAccount;
import business.MangClient;
import business.MangTransaction;
import dataacces.User;
import dataacces.TransactionOperation;
import java.awt.Dimension;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class UserPannel extends javax.swing.JFrame {

    /**
     * Creates new form UserPannel
     */
    public UserPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cnpLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        addCButton = new javax.swing.JButton();
        cnpField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nrContLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        nrContText = new javax.swing.JTextField();
        AmountText = new javax.swing.JTextField();
        updateCButton = new javax.swing.JButton();
        deleteCButton = new javax.swing.JButton();
        listMoreCButton = new javax.swing.JButton();
        listOneCButton = new javax.swing.JButton();
        addAButton = new javax.swing.JButton();
        updateAButton = new javax.swing.JButton();
        deleteAButton = new javax.swing.JButton();
        listMoreAButton = new javax.swing.JButton();
        listOneAButton = new javax.swing.JButton();
        transfetButton = new javax.swing.JButton();
        GASButton = new javax.swing.JButton();
        WATERButton = new javax.swing.JButton();
        ElectricaButton = new javax.swing.JButton();
        utilitiesLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sourceLabel = new javax.swing.JLabel();
        sourceText = new javax.swing.JTextField();
        destinationLabel = new javax.swing.JLabel();
        destinationText = new javax.swing.JTextField();
        user_idLabel = new javax.swing.JLabel();
        user_idText = new javax.swing.JTextField();
        descriereLabel = new javax.swing.JLabel();
        descriereText = new javax.swing.JTextField();
        transactionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 700));
        setName("UserPannel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 700));

        cnpLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        cnpLabel.setForeground(new java.awt.Color(0, 102, 102));
        cnpLabel.setText("CNP/CUI");

        nameLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 102, 102));
        nameLabel.setText("Name");

        jLabel3.setBackground(new java.awt.Color(255, 0, 51));
        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Client");

        addressLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(0, 102, 102));
        addressLabel.setText("Address");

        phoneLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(0, 102, 102));
        phoneLabel.setText("Phone");

        addCButton.setBackground(new java.awt.Color(0, 102, 102));
        addCButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        addCButton.setText("Add a Client");
        addCButton.setToolTipText("If you add a Client, an Account will be added automatically");
        addCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCButtonActionPerformed(evt);
            }
        });

        cnpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Account ");

        nrContLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        nrContLabel.setForeground(new java.awt.Color(0, 102, 102));
        nrContLabel.setText("Account Number");

        amountLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(0, 102, 102));
        amountLabel.setText("Amount");

        updateCButton.setBackground(new java.awt.Color(0, 102, 102));
        updateCButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        updateCButton.setText("Update a Client");
        updateCButton.setToolTipText("Fill in Client fields for update. The CNP has to be 13 characters!");
        updateCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCButtonActionPerformed(evt);
            }
        });

        deleteCButton.setBackground(new java.awt.Color(0, 102, 102));
        deleteCButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        deleteCButton.setText("Delete a Client");
        deleteCButton.setToolTipText("Fill in the CNP field.");
        deleteCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCButtonActionPerformed(evt);
            }
        });

        listMoreCButton.setBackground(new java.awt.Color(0, 102, 102));
        listMoreCButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        listMoreCButton.setText("List clients");
        listMoreCButton.setToolTipText("View all clients");
        listMoreCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMoreCButtonActionPerformed(evt);
            }
        });

        listOneCButton.setBackground(new java.awt.Color(0, 102, 102));
        listOneCButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        listOneCButton.setText("List a client by CNP/CUI");
        listOneCButton.setToolTipText("Fill in the CNP to view a specific Client");
        listOneCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOneCButtonActionPerformed(evt);
            }
        });

        addAButton.setBackground(new java.awt.Color(0, 102, 102));
        addAButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        addAButton.setText("Add an Account");
        addAButton.setToolTipText("Fill Account Number and amount and CNP for add an account.");
        addAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAButtonActionPerformed(evt);
            }
        });

        updateAButton.setBackground(new java.awt.Color(0, 102, 102));
        updateAButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        updateAButton.setText("Update an account");
        updateAButton.setToolTipText("Fill Account Number and Amount to update an Account.");
        updateAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAButtonActionPerformed(evt);
            }
        });

        deleteAButton.setBackground(new java.awt.Color(0, 102, 102));
        deleteAButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        deleteAButton.setText("Delete an account");
        deleteAButton.setToolTipText("Fill the Account Number for delete an Account.");
        deleteAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAButtonActionPerformed(evt);
            }
        });

        listMoreAButton.setBackground(new java.awt.Color(0, 102, 102));
        listMoreAButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        listMoreAButton.setText("List accounts");
        listMoreAButton.setToolTipText("View all Accounts.");
        listMoreAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMoreAButtonActionPerformed(evt);
            }
        });

        listOneAButton.setBackground(new java.awt.Color(0, 102, 102));
        listOneAButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        listOneAButton.setText("List an account by its number");
        listOneAButton.setToolTipText("Fill in the Account Number to view a specific Account");
        listOneAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOneAButtonActionPerformed(evt);
            }
        });

        transfetButton.setBackground(new java.awt.Color(0, 102, 102));
        transfetButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        transfetButton.setText("Make a transfer");
        transfetButton.setToolTipText("Fill Sorse, Destination, Your ID, Description and Amount to make a transfer.");
        transfetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfetButtonActionPerformed(evt);
            }
        });

        GASButton.setBackground(new java.awt.Color(0, 102, 102));
        GASButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        GASButton.setText("GAS");
        GASButton.setToolTipText("Fill the source code and amount to pay the GAS bill.");
        GASButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GASButtonActionPerformed(evt);
            }
        });

        WATERButton.setBackground(new java.awt.Color(0, 102, 102));
        WATERButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        WATERButton.setText("WATER");
        WATERButton.setToolTipText("Fill the source code and amount to pay the WATER bill.");
        WATERButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WATERButtonActionPerformed(evt);
            }
        });

        ElectricaButton.setBackground(new java.awt.Color(0, 102, 102));
        ElectricaButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        ElectricaButton.setText("ELECTRICA");
        ElectricaButton.setToolTipText("Fill the source code and amount to pay the ELECTRICA bill.");
        ElectricaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElectricaButtonActionPerformed(evt);
            }
        });

        utilitiesLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        utilitiesLabel.setForeground(new java.awt.Color(0, 102, 102));
        utilitiesLabel.setText("Pay some utilities:");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton1.setText("LOG-OUT");
        jButton1.setToolTipText("Press for LOG-OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Transfers");

        sourceLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        sourceLabel.setForeground(new java.awt.Color(0, 102, 102));
        sourceLabel.setText("Source");

        sourceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTextActionPerformed(evt);
            }
        });

        destinationLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        destinationLabel.setForeground(new java.awt.Color(0, 102, 102));
        destinationLabel.setText("Destination");

        user_idLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        user_idLabel.setForeground(new java.awt.Color(0, 102, 102));
        user_idLabel.setText("Your ID:");

        descriereLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        descriereLabel.setForeground(new java.awt.Color(0, 102, 102));
        descriereLabel.setText("Description");

        transactionButton.setBackground(new java.awt.Color(0, 102, 102));
        transactionButton.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        transactionButton.setText("Transaction history for an Account");
        transactionButton.setToolTipText("Fill in the Account Number field for view its transaction history");
        transactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateCButton)
                                    .addComponent(deleteCButton)
                                    .addComponent(addCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listMoreCButton)
                                    .addComponent(listOneCButton)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(transfetButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(transactionButton, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(utilitiesLabel)
                            .addComponent(GASButton)
                            .addComponent(ElectricaButton)
                            .addComponent(WATERButton))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listMoreAButton)
                            .addComponent(listOneAButton)
                            .addComponent(deleteAButton)
                            .addComponent(updateAButton)
                            .addComponent(addAButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nrContLabel)
                                    .addComponent(amountLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nrContText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(sourceText, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(descriereText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phoneLabel)
                                .addComponent(addressLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cnpLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameLabel)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cnpField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(descriereLabel)
                                        .addComponent(sourceLabel)
                                        .addComponent(destinationLabel)
                                        .addComponent(jLabel2)
                                        .addComponent(user_idLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(destinationText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(411, 411, 411)
                            .addComponent(user_idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jButton1)))
                .addContainerGap(596, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AmountText, addressField, cnpField, nameField, nrContText, phoneField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ElectricaButton, GASButton, WATERButton, addAButton, addCButton, deleteAButton, deleteCButton, listMoreAButton, listMoreCButton, listOneAButton, listOneCButton, transactionButton, transfetButton, updateAButton, updateCButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {descriereText, destinationText, sourceText, user_idText});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpLabel)
                    .addComponent(nrContLabel)
                    .addComponent(nrContText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceLabel)
                    .addComponent(sourceText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amountLabel)
                        .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(destinationLabel)
                        .addComponent(destinationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user_idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressLabel)
                        .addComponent(user_idLabel)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriereLabel)
                    .addComponent(descriereText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(transactionButton)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfetButton)
                    .addComponent(addAButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCButton)
                    .addComponent(updateAButton)
                    .addComponent(utilitiesLabel))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCButton)
                    .addComponent(deleteAButton)
                    .addComponent(GASButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listMoreAButton)
                    .addComponent(listMoreCButton)
                    .addComponent(ElectricaButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listOneAButton)
                            .addComponent(listOneCButton))
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WATERButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(22, 22, 22))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AmountText, addressField, cnpField, nameField, nrContText, phoneField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ElectricaButton, GASButton, WATERButton, addAButton, addCButton, deleteAButton, deleteCButton, listMoreAButton, listMoreCButton, listOneAButton, listOneCButton, transactionButton, transfetButton, updateAButton, updateCButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {descriereText, destinationText, sourceText, user_idText});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LOGIN login=new LOGIN();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sourceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceTextActionPerformed

    private void addCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCButtonActionPerformed
        // TODO add your handling code here:
        MangClient client=new MangClient();
        String CNP=cnpField.getText();
        String nume=nameField.getText();
        String address=addressField.getText();
        String phone=phoneField.getText();
        String rezultat=client.addC(CNP, nume, address, phone);
        if(rezultat.equals("Inserted successfully"))
        {
            JOptionPane.showMessageDialog(null, "Adaugat cu succes");
        }
        else
            JOptionPane.showMessageDialog(null, "Nu s-a putut face adaugarea");
    }//GEN-LAST:event_addCButtonActionPerformed

    private void transfetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfetButtonActionPerformed
        // TODO add your handling code here:
        String sursa=sourceText.getText();
        String destinatie=destinationText.getText();
        Float amount=parseFloat(AmountText.getText());
        int user_id=parseInt(user_idText.getText());
        String descriere=descriereText.getText();
        MangTransaction tranzactie=new MangTransaction();
        String validare=tranzactie.Tranzactie(sursa, destinatie, amount, descriere, user_id);
        if(validare.equals("Tranzactie efectuata cu succes"))
            JOptionPane.showMessageDialog(null, "Tranzactie efectuata cu succes");
        else
           JOptionPane.showMessageDialog(null, "Nu s-a putut efectua tranzactia"); 
    }//GEN-LAST:event_transfetButtonActionPerformed

    private void updateCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCButtonActionPerformed
        // TODO add your handling code here:
        MangClient client=new MangClient();
        String CNP=cnpField.getText();
        String nume=nameField.getText();
        String address=addressField.getText();
        String phone=phoneField.getText();
        String rezultat=client.updateC(CNP, nume, address, phone);
        if(rezultat.equals("Updated successfully"))
        {
            JOptionPane.showMessageDialog(null, "Updated successfully");
        }
        else
            JOptionPane.showMessageDialog(null, "Not updated");
    }//GEN-LAST:event_updateCButtonActionPerformed

    private void deleteCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCButtonActionPerformed
        // TODO add your handling code here:
        MangClient client=new MangClient();
        String CNP=cnpField.getText();
        String rezultat=client.deleteC(CNP);
        if(rezultat.equals("Deleted successfully"))
        {
            JOptionPane.showMessageDialog(null, "Deleted successfully");
        }
        else
            JOptionPane.showMessageDialog(null, "Deleted updated");
    }//GEN-LAST:event_deleteCButtonActionPerformed

    private void listMoreCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMoreCButtonActionPerformed
        // TODO add your handling code here:
        MangClient client=new MangClient();
        DefaultTableModel userModel=client.getC();
        JTable userTable=new JTable(userModel);
        JDialog dialog=new JDialog();
        dialog.setPreferredSize(new Dimension(650,300));
	dialog.setLocationRelativeTo(null);
	dialog.setTitle("Clients");
        JScrollPane scrollPane3 = new JScrollPane(userTable);
        scrollPane3.setBounds(10, 50, 950, 120);
	scrollPane3.setEnabled(false);
	dialog.add(scrollPane3);
	dialog.pack();
	dialog.setVisible(true);
    }//GEN-LAST:event_listMoreCButtonActionPerformed

    private void listOneCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOneCButtonActionPerformed
        // TODO add your handling code here:
        String CNP=cnpField.getText();
        //System.out.print("1");
        MangClient client=new MangClient();
        DefaultTableModel userModel=client.getCs(CNP);
        //System.out.print("1");
        JTable userTable=new JTable(userModel);
        JDialog dialog=new JDialog();
        dialog.setPreferredSize(new Dimension(650,300));
	dialog.setLocationRelativeTo(null);
	dialog.setTitle("Client with "+CNP+" CNP");
        JScrollPane scrollPane3 = new JScrollPane(userTable);
        scrollPane3.setBounds(10, 50, 950, 120);
	scrollPane3.setEnabled(false);
	dialog.add(scrollPane3);
	dialog.pack();
	dialog.setVisible(true);
    }//GEN-LAST:event_listOneCButtonActionPerformed

    private void addAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAButtonActionPerformed
        // TODO add your handling code here:
        String CNP=cnpField.getText();
        String nr_cont=nrContText.getText();
        Date date=new Date();
        Float amount=parseFloat(AmountText.getText());
        MangAccount acc=new MangAccount();
        String rezultat=acc.addA(nr_cont, CNP, date, amount);
        if(rezultat.equals("Account created!"))
        {
            JOptionPane.showMessageDialog(null, "Account created!");
        }
        else
            JOptionPane.showMessageDialog(null, "Account not created!");
        
    }//GEN-LAST:event_addAButtonActionPerformed

    private void deleteAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAButtonActionPerformed
        // TODO add your handling code here:
        String nr_cont=nrContText.getText();
         MangAccount acc=new MangAccount();
         String rezultat=acc.deleteA(nr_cont);
         if(rezultat.equals("Deleted successfully"))
        {
            JOptionPane.showMessageDialog(null, "Deleted successfully");
        }
        else
            JOptionPane.showMessageDialog(null, "Account not deleted!");
    }//GEN-LAST:event_deleteAButtonActionPerformed

    private void updateAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAButtonActionPerformed
        // TODO add your handling code here:
        String CNP=cnpField.getText();
        String nr_cont=nrContText.getText();
        Date date=new Date();
        Float amount=parseFloat(AmountText.getText());
        MangAccount acc=new MangAccount();
        String rezultat=acc.updateA(nr_cont, CNP, date, amount);
        if(rezultat.equals("Updated successfully"))
        {
            JOptionPane.showMessageDialog(null, "Updated successfully!");
        }
        else
            JOptionPane.showMessageDialog(null, "Account not updated!");
    }//GEN-LAST:event_updateAButtonActionPerformed

    private void listMoreAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMoreAButtonActionPerformed
        // TODO add your handling code here:
        MangAccount client=new MangAccount();
        DefaultTableModel userModel=client.getA();
        JTable userTable=new JTable(userModel);
        JDialog dialog=new JDialog();
        dialog.setPreferredSize(new Dimension(650,300));
	dialog.setLocationRelativeTo(null);
	dialog.setTitle("Accounts");
        JScrollPane scrollPane3 = new JScrollPane(userTable);
        scrollPane3.setBounds(10, 50, 950, 120);
	scrollPane3.setEnabled(false);
	dialog.add(scrollPane3);
	dialog.pack();
	dialog.setVisible(true);
    }//GEN-LAST:event_listMoreAButtonActionPerformed

    private void listOneAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOneAButtonActionPerformed
        // TODO add your handling code here:
        String nr_cont=nrContText.getText();
        //System.out.print("1");
        MangAccount acc=new MangAccount();
        DefaultTableModel userModel=acc.getCs(nr_cont);
        //System.out.print("1");
        JTable userTable=new JTable(userModel);
        JDialog dialog=new JDialog();
        dialog.setPreferredSize(new Dimension(650,300));
	dialog.setLocationRelativeTo(null);
	dialog.setTitle("Account with "+nrContText+" number");
        JScrollPane scrollPane3 = new JScrollPane(userTable);
        scrollPane3.setBounds(10, 50, 950, 120);
	scrollPane3.setEnabled(false);
	dialog.add(scrollPane3);
	dialog.pack();
	dialog.setVisible(true);
    }//GEN-LAST:event_listOneAButtonActionPerformed

    private void GASButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GASButtonActionPerformed
        // TODO add your handling code here:
        String sursa=sourceText.getText();
        String payG="1.2346913480231234e16";
        Float amount=parseFloat(AmountText.getText());
        int user_id=parseInt(user_idText.getText());
        MangTransaction tranzactie=new MangTransaction();
        String validare=tranzactie.PayGas(sursa, payG, amount, "Gas Bill", user_id);
        if(validare.equals("Tranzactie efectuata cu succes"))
            JOptionPane.showMessageDialog(null, "Tranzactie efectuata cu succes");
        else
           JOptionPane.showMessageDialog(null, "Nu s-a putut efectua tranzactia"); 
    }//GEN-LAST:event_GASButtonActionPerformed

    private void ElectricaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElectricaButtonActionPerformed
        // TODO add your handling code here:
        String sursa=sourceText.getText();
        String payE="";
        Float amount=parseFloat(AmountText.getText());
        int user_id=parseInt(user_idText.getText());
        MangTransaction tranzactie=new MangTransaction();
        String validare=tranzactie.PayGas(sursa, payE, amount, "Electrica Bill", user_id);
        if(validare.equals("Tranzactie efectuata cu succes"))
            JOptionPane.showMessageDialog(null, "Tranzactie efectuata cu succes");
        else
           JOptionPane.showMessageDialog(null, "Nu s-a putut efectua tranzactia"); 
    }//GEN-LAST:event_ElectricaButtonActionPerformed

    private void WATERButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WATERButtonActionPerformed
        // TODO add your handling code here:
        String sursa=sourceText.getText();
        String payW="";
        Float amount=parseFloat(AmountText.getText());
        int user_id=parseInt(user_idText.getText());
        MangTransaction tranzactie=new MangTransaction();
        String validare=tranzactie.PayGas(sursa, payW, amount, "Water Bill", user_id);
        if(validare.equals("Tranzactie efectuata cu succes"))
            JOptionPane.showMessageDialog(null, "Tranzactie efectuata cu succes");
        else
           JOptionPane.showMessageDialog(null, "Nu s-a putut efectua tranzactia"); 
    }//GEN-LAST:event_WATERButtonActionPerformed

    private void transactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionButtonActionPerformed
        // TODO add your handling code here:
        String nr_cont=nrContText.getText();
        //System.out.print("1");
        TransactionOperation acc=new TransactionOperation();
        DefaultTableModel userModel=acc.TransactionHistory(nr_cont);
        //System.out.print("1");
        JTable userTable=new JTable(userModel);
        JDialog dialog=new JDialog();
        dialog.setPreferredSize(new Dimension(650,300));
	dialog.setLocationRelativeTo(null);
	dialog.setTitle("Transaction history for:  "+nr_cont);
        JScrollPane scrollPane3 = new JScrollPane(userTable);
        scrollPane3.setBounds(10, 50, 950, 120);
	scrollPane3.setEnabled(false);
	dialog.add(scrollPane3);
	dialog.pack();
	dialog.setVisible(true);
    }//GEN-LAST:event_transactionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPannel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountText;
    private javax.swing.JButton ElectricaButton;
    private javax.swing.JButton GASButton;
    private javax.swing.JButton WATERButton;
    private javax.swing.JButton addAButton;
    private javax.swing.JButton addCButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField cnpField;
    private javax.swing.JLabel cnpLabel;
    private javax.swing.JButton deleteAButton;
    private javax.swing.JButton deleteCButton;
    private javax.swing.JLabel descriereLabel;
    private javax.swing.JTextField descriereText;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JTextField destinationText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton listMoreAButton;
    private javax.swing.JButton listMoreCButton;
    private javax.swing.JButton listOneAButton;
    private javax.swing.JButton listOneCButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nrContLabel;
    private javax.swing.JTextField nrContText;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel sourceLabel;
    private javax.swing.JTextField sourceText;
    private javax.swing.JButton transactionButton;
    private javax.swing.JButton transfetButton;
    private javax.swing.JButton updateAButton;
    private javax.swing.JButton updateCButton;
    private javax.swing.JLabel user_idLabel;
    private javax.swing.JTextField user_idText;
    private javax.swing.JLabel utilitiesLabel;
    // End of variables declaration//GEN-END:variables
}
